name: Java CI with Gradle

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run application
        run: java -jar app-ibank-build-for-testers.jar &

      - name: Wait for application to start
        run: sleep 10

      - name: Run tests with detailed info
        run: ./gradlew test -Dselenide.headless=true --info